# Generated by Django 4.1.1 on 2022-10-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_college_course_examdate_studentchoise_ws_delete_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ws',
            old_name='start',
            new_name='start1',
        ),
        migrations.RenameField(
            model_name='ws',
            old_name='time',
            new_name='start2',
        ),
        migrations.AddField(
            model_name='ws',
            name='time1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ws',
            name='time2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
