# Generated by Django 4.1.1 on 2022-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_rename_start_ws_start1_rename_time_ws_start2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdate',
            name='date',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
