# Generated by Django 4.1.1 on 2022-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_alter_examdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ps',
            field=models.CharField(blank=True, default='-', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirement',
            field=models.CharField(blank=True, default='-', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='synthesis',
            field=models.CharField(blank=True, default='-', max_length=256),
        ),
    ]
